### ISSUE TITLE
Bugs: hide-and-seek

### ISSUE THREAD

**Issue by TimmyChan99** [HAMMAS-SALEEM/Portfolio#19]
In your localStorage.js file, there are some issues. 

- When you store the data using addEventListener try to replace `submit` with `change`.
- When you load the page, check first if there is previously stored data or not.
- Try to document your work it will make it easy to read.

**Comment by HAMMAS-SALEEM** [comment]
Thanks for reaching out to me and telling me issues in my project. I shall definitely work on them and improve my project. 👍 

Feel free in opening issues and to leave comments in my repositories. 😄
